### ISSUE TITLE
extra white space to the right of nodes

### ISSUE THREAD

**Issue by maenpaa24** [dudebout/matrix.skeleton#3] opened 2020-02-08 23:00 UTC
I am trying to depict more than one matrix with tikz with the tikz libraries matrix and matrix.skeleton because later I want to highlight some things and so on.

This would be my mwe:

```
\documentclass{standalone}
\usepackage{tikz}
\usetikzlibrary{matrix}
\usetikzlibrary{matrix.skeleton}
\usetikzlibrary{calc}

\begin{document}


\begin{tikzpicture}


\matrix (X) [matrix of math nodes,
			label skeleton,
             left delimiter  = (,
             right delimiter = )] at (0,0)
{%
  \vdots & \vdots &  & \vdots  \\
  x & x & \cdots & x \\
  \vdots & \vdots &  & \vdots  \\
  x & x & \cdots & x\\
  \vdots & \vdots &  & \vdots  \\
  x & x & \cdots & x\\
  \vdots & \vdots &  & \vdots  \\
  x & x & \cdots & x\\
  \vdots & \vdots &  & \vdots  \\
  x & x & \cdots & x\\
};

\matrix (U) [matrix of math nodes,
			label skeleton,
             left delimiter  = (,
             right delimiter = )] at (4,0)
{
  \vdots  \\
  u\\
  \vdots \\
  u\\
  \vdots \\
  u\\
  \vdots \\
  u\\
  \vdots \\
  u\\
};

\end{tikzpicture}
\end{document}
```

outcome from mwe:

![GyNcs](https://user-images.githubusercontent.com/19935414/74093182-f0afe880-4ace-11ea-806c-f19310564105.png)

which creates an extra white space to the right of the second matrix. I have notice that it happens when I make use of the matrix.skeleton library by means of label skeleton. However, I can not find the solution in the manual of the package from CTAN.

**Comment by dudebout** [comment] 2020-02-09 14:32
This is a duplicate of #1. When I looked into it, I noted that [the use of at positioning was causing issues](https://github.com/dudebout/matrix.skeleton/issues/1#issuecomment-49391401). I don't have a fix for it, and have not used this library in years. Maybe [this workaround](https://github.com/dudebout/matrix.skeleton/issues/1#issuecomment-50510311) will work for you.

**Closed as completed by dudebout** 2020-02-09 14:32 UTC

**Comment by maenpaa24** [comment] 2020-02-09 14:36
Ok, thanks.
